language: php
sudo: false
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/symfony-bridge/.phpunit

env:
  global:
    - PHPUNIT_FLAGS="-v"
    - SYMFONY_PHPUNIT_DIR="$HOME/symfony-bridge/.phpunit"

matrix:
  fast_finish: true
  include:
    - php: 7.2
      install:
        - travis_retry composer update -n --prefer-lowest --prefer-stable --prefer-dist
    - php: 7.3
      env: SYMFONY_REQUIRE="3.4.*"
    - php: 7.3
      env: SYMFONY_REQUIRE="4.3.*"
    - php: 7.3
      env: SYMFONY_REQUIRE="4.4.*"
    - php: 7.3
      env: SYMFONY_REQUIRE="5.0.*"
    - php: 7.3
    - php: 7.4snapshot
    - php: 7.3
      env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"

  allow_failures:
    - env: COVERAGE=true

before_install:
  - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
  - composer self-update
  - composer global require --no-scripts --no-plugins symfony/flex

install:
  - travis_retry composer update ${COMPOSER_FLAGS} -n --prefer-dist --prefer-stable

script:
  - composer validate --strict --no-check-lock
  - vendor/bin/phpunit
